[package]
name = "prpr-pbc"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
pollster = { workspace = true }
prpr = { workspace = true }
